.TH template 1
.SH NAME
template \- a C Project Template
.SH SYNOPSIS
.PP
template [options] <arguments>
.PP
[ --help | -h ]
.PP
[ --version | -v ]
.PP
[ --trace | -t ] <filename>
.PP
[ --debug-level | -d ] <number>
.PP
[ --colored-log | -c ]
.PP
[ --conf-filename | -C ] <filename>
.PP
.SH DESCRIPTION
.PP 
template is a C Project Template
.SH OPTIONS
.TP
.BR --help, \ -h
Show this message and exit
.TP
.BR --version, \ -v 
Show the version and exit
.TP
.BR --trace, \ -t
<file> is the path of the debug file
.TP
.BR --debug-level, \ -l
<number> is the level of debug level
.TP
.BR --colored-log, \ -c
Set a colored log
.TP
.BR --conf-filename, \ -C
<file> is the path of the .conf file of software
.SH BUGS
.PP
For reporting bugs, send a email to <email@example.com>
.SH AUTHOR
.PP
DEV_NAME <email@example.com>
